### ISSUE TITLE
'common' probably not a good library name

### ISSUE THREAD

**Issue by vineetbansal** [vineetbansal/Cryo#12]
I think the submodules within the 'common' module should be deemed common based on their location in the hierarchy w.r.t. the cryo package (i.e. by being immediately beneath the cryo package), not as a result of the name of the module they're in ('common'). So in effect, the basis/utils/imaging module would be submodules within cryo, and everything not in a specific package like 'cov3d' or 'denoising' is common by definition.

**Comment by junchaoxia** [comment]
I am not sure that I get your idea. Do you mean that basis/utils/image/nfft used to be under cov3d should be parallel to cov3d and denoising?  I originally like to organize them in such a way that submodules required by more than two main modules (such as cov3d and denoising)  should be under the common folder. But It is totally fine to me as long as they are unique to the whole package  and easy to find for other developers.

**Comment by janden** [comment]
I think what @vineetbansal is saying is that if there's code that's common to two submodules (such as cov3d and denosing), that would itself be a separate submodule (like nufft). The fact that its in the same folder as cov3d and denoising makes it "common" in the sense that it's in the same level in the directory structure.

What I think @junchaoxia is getting at (correct me if I'm wrong), is that we may want a "catch-all" submodule for small utility functions that don't necessarily fit within a larger submodule (like padding, unpadding, dealing with temp files, etc). Maybe having something like a "utils" submodule would be good for this.

**Comment by janden** [comment]
Again, if I totally misinterpreted, please let me know!

**Comment by vineetbansal** [comment]
Yes..that's what I was getting at..anything that is 'common' to cryo-em processing (and not tied to specific workflows like covariance/denoising), like the basis objects, is in the purview of the codebase, so putting it in another 'common' submodule is unnecessary. I agree that small functions should be in utils (either directly or within a further submodule of utils if too specialized).

**Comment by junchaoxia** [comment]
OK. I think we have the agreement so we can go ahead to rearrange the subfolders under the cov3d.

**Comment by vineetbansal** [comment]
Fixed in abade50bdd89150f4f67d7b9b8c326607912ee07
