### ISSUE TITLE
Basis base class constructor not called

### ISSUE THREAD

**Issue by vineetbansal** [vineetbansal/Cryo#13]
Neither of the 2 subclasses are calling the base constructor, indicating either the base __init__ is not needed, or that the subclasses should (at least partially) be constructed by delegating to super()

https://github.com/vineetbansal/Cryo/blob/9637bd48f10bb58c091bdcc7afec865cb65cb471/cryo/common/basis/__init__.py#L17

**Comment by junchaoxia** [comment]
This issue has be fixed in the commit [https://github.com/vineetbansal/Cryo/commit/3d15e27d204671c5d5be7b8bb54ff10401acdf92 ]()
