### ISSUE TITLE
Unit tests for evaluate/evaluate_t missing for basis objects

### ISSUE THREAD

**Issue by vineetbansal** [vineetbansal/Cryo#15]
To solve issue #14, it would be very useful to have unit tests in place for evaluate/evaluate_t methods for both FBBasis and HBBasis objects.

**Comment by vineetbansal** [comment]
@junchaoxia .. I've added 2 new tests in test_HBbasis.py .. testHBBasisEvaluate/testHBBasisEvaluate_t. I don't have a workflow for the 2d basis case to be able to add corresponding tests/data for the FBBasis class. Are you able to do this? If so, I can then handle issue #14 (for both the 2d and 3d case) and make sure the tests still pass.

**Comment by junchaoxia** [comment]
@vineetbansal Me neither for a quick solution. Probably you can leave it as is unless @janden has a quick example. I will fix it when I come to do unittest for the new basis, Fast FB in two dimensions.

**Comment by vineetbansal** [comment]
@junchaoxia - no problem. I really just need matrices of the correct dimensions to create a baseline test case before tackling that issue .. I'll make something up.

**Comment by vineetbansal** [comment]
Added in 6415f77eb10ccbc0defab760c2ede33a4eeaaaac
