### ISSUE TITLE
Simplify constructor for Basis class

### ISSUE THREAD

**Issue by vineetbansal** [vineetbansal/Cryo#17]
It may be a good idea to separate the constructor into just the basic variable initialization statements plus a `build()` function that will take those variables and compute any dependent values, such as Bessel zeros.

_Originally posted by @janden in https://github.com/_render_node/MDE3OlB1bGxSZXF1ZXN0UmV2aWV3MjA5ODAxMTg4/pull_request_reviews/more_threads_

**Comment by junchaoxia** [comment]
The issue has be fixed in 
[https://github.com/vineetbansal/Cryo/commit/3d15e27d204671c5d5be7b8bb54ff10401acdf92]()
