### ISSUE TITLE
need to change "cov3d" in environment.yml to "cryo"

### ISSUE THREAD

**Issue by junchaoxia** [vineetbansal/Cryo#18]
@vineetbansal  The name in the environment.yml is still called cov3d instead of new one "cryo".  It will run into a problem when setting the environment without removing the old one.

**Comment by vineetbansal** [comment]
Good catch .. fixed in aefb01d44351e4dcf0339540d89f0a1a216871b9
Travis never caught the error because we override the environment name in .travis.yml:
```
conda env create -n test-environment -f environment.yml
```
