### ISSUE TITLE
add 2D support in nfft   

### ISSUE THREAD

**Issue by junchaoxia** [vineetbansal/Cryo#21]
@vineetbansal We need to add nufft support for 2D images and move nufft folder out of cov3d to be shared with other major modules.

**Comment by vineetbansal** [comment]
@junchaoxia .. not sure I understand "add nufft support for 2D images". The existing Plan class should be able to deal with both 2d images and 3d volumes (even if the comments indicate otherwise). I can move the nfft module out one level

**Comment by junchaoxia** [comment]
@vineetbansal Thanks. Great to know that not many efforts are needed. I only found anufft3 not anufft2. If anufft3 is working for 2D case, that should be fine. We also need to clean the comments which might be misleading.

**Comment by junchaoxia** [comment]
@vineetbansal  I have cloned the latest development branch and the tests have be passed.
