### ISSUE TITLE
Possible Bug

### ISSUE THREAD

**Issue by vineetbansal** [vineetbansal/Cryo#35]
This very likely needs to be a '2' instead of a '3'

https://github.com/vineetbansal/Cryo/blob/87746ce9fdcc7934e416af5b2f3e04d6094964f9/src/cryo/utils/__init__.py#L402

**Comment by junchaoxia** [comment]
@vineetbansal It might be better to expand the unit tests in multiple 2D images. Then the unroll and roll dim functions become more obvious.

**Comment by vineetbansal** [comment]
Turns out this was a false alarm.

In general I agree. In this case though, the unit test for this function (`testVecToMatSymmIso`) is doing the right thing..it's testing the function on an input that has extra dimensions than it *needs* to have. Which is why it passes (when it should have failed had there been a bug). A closer inspection of the code reveals why:

```
    mat = vec_to_symmat(vec)
    mat, sz_roll = unroll_dim(mat, 3)
```

The first line has expanded the vector into a matrix, and thus the second line needs to have a 3 instead of a 2.
