### ISSUE TITLE
Add support for finufft

### ISSUE THREAD

**Issue by vineetbansal** [vineetbansal/Cryo#7]
A new facade nfft module that selects an appropriate backend (preferences driven by config.json) - at least finufft/pynfft

**Comment by janden** [comment]
There seems to be some clues as to how to do the installation [here](https://github.com/PrincetonUniversity/ASPIRE-Python/blob/master/tasks/install_finufftpy.sh). From what I understand, there are some issues with installing under macOS/Windows, but we should be able to work this out together with the developers.

**Comment by vineetbansal** [comment]
I was able to install finufft on Windows over the weekend, but it involved jumping through a lot of hoops. It's no more painful than getting pynfft to work though. I'm now trying to replicate the process on my official Windows machine and document every step of the process. The tweaks needed to the official finufft source to support Windows should be minimal .. perhaps I can share these with you?

**Comment by janden** [comment]
That's great news! Of course. You can also post an issue [here](https://github.com/flatironinstitute/finufft/issues).

**Comment by vineetbansal** [comment]
Support added. Needs documentation as per issue #10
